[package]
name = "icechip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chippers = { path = "../chip-8" }

[dependencies.iced]
version = "0.4.2"
features = ["canvas"]